kind: pipeline
type: kubernetes
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: porto.interlegis.leg.br/library/powerdns
    registry: porto.interlegis.leg.br
    mirror: https://registrycache.interlegis.leg.br
    pull: if-not-exists
    auto_tag: true
    dockerfile: pdns/Dockerfile
    username:
      from_secret: porto_user
    password:
      from_secret: porto_pw
